---
# tasks file for config-lb-for-router
- name: Check that the LB service is present on host
  service:
    name: haproxy
    enabled: yes
  register: haproxy_exist

- name: Fail the tasks if service not present
  fail:
    msg: These tasks can only be run when haproxy is present on the host
  when: not haproxy_exist.enabled | bool
    
- name: Copy HAProxy config to the Load balancer
  template:
    src: haproxy.config.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
    group: root
    owner: root 

- name: Restart the HAProxy service
  service:
    state: restarted
    name: haproxy
