- name: Create Certificate directory
  file:
    state: directory
    path: "{{ external_registry_cert_dir }}"
    mode: 0755
    owner: root
    group: root
  when:
    - external_registry_cert_dir is defined and external_registry_cert_dir | length > 0 

- name: Copy certifcate to directory created above
  copy:
    remote_src: yes
    src: "{{ external_registry_cert }}"
    dest: "{{ external_registry_cert_dir }}"
  when: 
    - external_registry_cert is defined and external_registry_cert | length > 0
